### ISSUE TITLE
Furni bigger than 1x1

### ISSUE THREAD

**Issue by Alex-Habbz** [Quackster/Elias#2]
Can only covert 1x1 furni that fits on 1 tile.

You can convert bigger furni but you have to set it as 1x1 in database to be able to use it and then you can walk through half of it.

If you set it bigger than 1x1 then the furni only shows as white box.

Tried with loads of furni bigger than 1x1 and all is the same.

**Comment by Quackster** [comment]
Configure your furnidata correctly where the length and width is specified.

**Comment by Alex-Habbz** [comment]
Ahh thanks, will try now. I thought the furnidata was just to see if it was a floor or wall item.

**Comment by Alex-Habbz** [comment]
It worked, thank you.
