### ISSUE TITLE
Doesnt generate its own small ccts.

### ISSUE THREAD

**Issue by Alex-Habbz** [Quackster/Elias#3]
When having small furni and generate modern set to true, it throws a null pointer exception. When only one of them is set to true it only generates the normal cct and not the small one, this means none of the furni works in big rooms.

**Comment by Quackster** [comment]
Send me the SWF you're using along with the EliasConfig.xml that produces this error

**Comment by Alex-Habbz** [comment]
Yeh sure, ive added greek_c15_bench which is only one of them but most of the SWFS do the same thing.

http://www.mediafire.com/file/tce9dr47rgmdyz0/Files.zip/file

**Comment by Quackster** [comment]
Thank you. I'll look into it when I have time. I have been very busy recently.

**Comment by Quackster** [comment]
Should be fixed with commit: 076f7f9fbb23c43cdbf9a10a9b02850d67c65bbf

New release: https://github.com/Quackster/Elias/releases/tag/v0.3

**Comment by Alex-Habbz** [comment]
Thank you, I have tested and it seems to be converting them to small furni now and isn't throwing any errors however its only saving the normal ccts to the converted folder and not the small ccts.

![Capture](https://user-images.githubusercontent.com/33091120/82713744-fac3b480-9c83-11ea-8924-217456007a7c.PNG)

**Comment by Quackster** [comment]
It does work. I tested it before I did the v0.3 release.

![RawZDFqCcN](https://user-images.githubusercontent.com/1328523/82719564-3cd61000-9cef-11ea-92e4-e8e43b9add0a.gif)

**Comment by Alex-Habbz** [comment]
Yep, got it working, it was an issue with something I added to it but fixed it now, thank you.
